// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv ./env.d.ts`

interface CloudflareEnv {
	KV: KVNamespace;
	NEXT_PUBLIC_CDN_URL: "cdn.studiozephyr.art";
	R2: R2Bucket;
}
